"""add track_cache table

Revision ID: 7408f29eb6e3
Revises: g7h8i9j0k1l2
Create Date: 2026-05-05 23:33:52.975030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7408f29eb6e3'
down_revision: Union[str, None] = 'g7h8i9j0k1l2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spotify_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('artist', sa.String(length=256), nullable=False),
    sa.Column('album_name', sa.String(length=256), nullable=True),
    sa.Column('album_id', sa.String(length=64), nullable=True),
    sa.Column('release_date', sa.String(length=16), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('explicit', sa.Integer(), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('artist_ids_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('track_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_cache_spotify_id'), ['spotify_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_cache_spotify_id'))

    op.drop_table('track_cache')
    # ### end Alembic commands ###
